rails/rails-contributors

app/controllers/commits_controller.rb
app/controllers/contributors_controller.rb
app/helpers/application_helper.rb
app/models/commit.rb
app/models/contributor.rb
app/views/commits/index.html.erb
app/views/contributors/_contributor.html.erb
app/views/contributors/index.html.erb
app/views/shared/_window_sidebar.html.erb
config/routes.rb
test/controllers/commits_controller_test.rb
test/controllers/contributors_controller_test.rb

Hi Xavier!
On Fridays we send our weekly [This Week in Rails newsletter](http://rails-weekly.ongoodbits.io) and link to the top contributors.
Come Monday that link breaks because `contributors/in-time-window/this-week` has already moved on. We, however, are a bit more nostalgic and would like a canonical reference to a given week.
We also don't know when weeks begin and end - all I see anymore is newsletter Fridays. Ideally we'd like to input a date and have the app figure out which week it's part of.
I've added this feature including date range ballooning. Then by linking to `contributors/in-week-of/2015-02-13` the coming Friday 13th we can really scare our readers :hocho:
cc @chancancode

Show a weeks contributions from a given iso8601 date.

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

I've recently made rails/rails commits that split my contribution count across multiple rows in http://contributors.rubyonrails.org/contributors. This resolves that. 
@fxn let me know if I need to do other changes. I've checked the 'Allow edits from maintainers' if it's a no brainer. Cheers! 🥂

Maps "Marc Ignacio" to "Marc Rendl Ignacio"

---

app/models/names_manager/hard_coded_authors.rb
test/credits/hard_coded_authors_test.rb

I wrote the authors of the commits incorrectly so Aaron and Tsukuru
didn't get credit. This fixes that mistake.
cc/ @fxn

Fix authors of 2 commits

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

CanonicalNames maps "kazuhiko@fdiary.net" to Kazuhiro since c94d9d7bf8b75d24f158176bfd8e9e9b30093b04, but Kazuhiko and Kazuhiro are different individuals (I've met both of them).

Kazuhiko is not Kazuhiro

---

README.md

While testing my mapping change, I wanted to confirm I was making the change properly. I found `Repo.sync` and it's comments helpful and thought others might want an easier place to find it.

add instructions for database population

---

Gemfile
Gemfile.lock
test/test_helper.rb

* For reducing gem to need to maintain, it replaced.
* We don't need no longer delorean or timecop.

Use ActiveSupport::Testing::TimeHelpers instead of delorean

---

app/models/contribution.rb

* Since Rails v5, belongs_to association set presence validator by default.

Remove needless validation in Contribution

---

Gemfile
Gemfile.lock

* It's no problem to upgrade rugged from 0.21.0 to 0.27.0.
* [CHANGELOG](https://github.com/libgit2/rugged/blob/master/CHANGELOG.md)

Upgrade rugged 0.21.0 to 0.27.0

---

Dockerfile

`ruby:2.4` is ubuntu, so build is failed. Seems it have to use `alpine` image (build is succeed)

Use alpine image in Dockerfile

---

app/views/layouts/_top_bar_content.html.erb

I've changed weblog (GitHub page)'s protocol.
See: Custom domains on GitHub Pages gain support for HTTPS
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Use https with weblog URI

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

Hello,
This pull request gives proper credit to @albertoalmagro (c.f. https://github.com/rails/rails/pull/34241#discussion_r227133308) since the commit refers to his full name while his Git name is in a shorter form (and thus, already got credit on Rails Contributors with the latter).
This change has been tested locally.
Have a nice day !

Fix credit for Alberto Almagro

---

db/migrate/20141101094005_initial_schema.rb
db/migrate/20150326181907_add_first_contribution_at_to_contributors.rb
db/migrate/20160512095609_rename_nmupdated.rb
db/schema.rb

Add migration versions so they can be ran on a new machine (instead of raising an error), and use `try` for nonexistent fill method.

Add migration versions

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

Currently `eileencodes` contributions are listed below [eileen-m-uchitelle](https://contributors.rubyonrails.org/contributors/eileen-m-uchitelle/commits) and [eileen-uchitelle](https://contributors.rubyonrails.org/contributors/eileen-uchitelle/commits). Let's put them together!

Unify credits for Eileen M. Uchitelle

---

config/environments/test.rb

action_view.finalize_compiled_template_methods is deprecated and setting it has
no effect. It generates a deprecation warning when running the tests, removing
the config removes the warning.

remove deprecated config

---

app/models/commit.rb
app/views/faqs/show.html.erb
test/models/commit_test.rb

Github added support for co-authored-by annotations to mark commits by multiple
authors, this patch makes it so that the app is able to understand this format
and attribute commits to the various committers correctly.
Fixes: #133
For this commit: https://github.com/rails/rails/commit/99e52ae7b1c621069f2971d2f352822f263efb49
This is what it looks like without the patch: 
This is what it looks like with the patch:
cc: @fxn

Add support for co-authored-by commits

---

app/models/commit.rb
test/models/commit_test.rb

In rails/rails@13e2102 I used `Co-Authored-By` instead of
`Co-authored-by`. GitHub accepts both and I found other instances in the
codebase. If the contributors app is going to support `Co-authored-by`
we should ignore the case so that everyone gets credit.

Ignore case for co-authored-by

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

I have two commits with different names:
1. [Muhammad](https://contributors.rubyonrails.org/contributors/muhammad/commits)
2. [Muhammad Muhammad Ibrahim](https://contributors.rubyonrails.org/contributors/muhammad-muhammad-ibrahim/commits)
This should list both of them under the second one.

Add mapping for Muhammad Muhammad Ibrahim

---

Capfile
config/deploy/production.rb

Puma 5.0 remove daemon support so we need to use systemd instead.

Use systemd instead of daemon version

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

3 names were created: [fatkodima](https://contributors.rubyonrails.org/contributors/fatkodima/commits), [fatkodima123](https://contributors.rubyonrails.org/contributors/fatkodima123/commits) and [Dima Fatko](https://contributors.rubyonrails.org/contributors/dima-fatko/commits). I want to have only `fatkodima`.

Dima Fatko -> fatkodima

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

I have two commits listed under [sabrams86](https://contributors.rubyonrails.org/contributors/sabrams86/commits) and [Steven Abrams](https://contributors.rubyonrails.org/contributors/steven-abrams/commits).
[steve-abrams](https://github.com/steve-abrams) is my Github username and I go by Steven Abrams, so I created this PR to consolidate the credits.

Add canonical name 'Steven Abrams'

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

This commit is not linked to me https://github.com/rails/rails/commit/90d5a5c2aba556053cbd3f5eea31fc855ba3bc9f Name is `Jean-François Labbé`
This one was linked: https://github.com/rails/rails/commit/34916855ca949262ceb80ca476d452b799c13c5d name is `jean-francois labbe`

Add Jean-François Labbé mapping

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

Having an "Umlaut" in your name basically breaks a lot of stuff, so I sometimes use "ae" instead 🙈

Add Niklas Häusele mapping

---

app/models/names_manager/hard_coded_authors.rb
test/credits/hard_coded_authors_test.rb

Seems like this comit is not linked to me (S. Brent Faulkner)
See: [CHANGELOG in commit](https://github.com/rails/rails/commit/83c6ba18899a9f797d79726ca0078bdf618ec3d4#diff-71625f744d6dd8a0ae8521ae8ab815d99c6472768cedff74344cc5b244f2897c)
See also: [original lighthouse record](https://rails.lighthouseapp.com/projects/8994/tickets/838-add-support-for-selective-resource-routes-2)

fix attribution for commit of original shallow routes implementation

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

I created this PR because both commits originated from the same GitHub account.

Add Takuma Yoshida mapping

---

app/assets/javascripts/application.js

We were toggling the sidebar regardless of whether it was open or closed. This caused the back button to close the sidebar on the desktop instead of opening it (because it was already open).

Only toggle sidebar if it is closed

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

Ref https://github.com/rails/rails/commit/773d640cf1d650356519acc9cb0bbc2c5c8de670

Add "Hartley McGuire" mapping for bad Coauthor

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

I've maintained the same email address, me@cpb.ca, as per: https://github.com/rails/rails/blob/5fa8793f02b58509a90eed69e8dc3d199f89b4ad/activerecord/CHANGELOG#L3
Thanks in advance!

Map 'Caleb' to 'Caleb Buxton'

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

Fixing a couple commits I made with a bad user name https://contributors.rubyonrails.org/contributors/andrew-novoselac-shopify-com/commits
🙇 thank you

Fix attribution for Andrew Novoselac

---

Gemfile
Gemfile.lock
config/deploy.rb
config/puma/production.rb

This error was found in the logs:
```
$ tail -50 current/log/puma_error.log
...
puma-5.6.8/lib/rack/version_restriction.rb:12:in `<top (required)>':
Puma 5 is not compatible with Rack 3, please upgrade to Puma 6 or higher. (StandardError)
```
We probably also need to deal with updating capistrano-puma:
https://github.com/seuros/capistrano-puma?tab=readme-ov-file#upgrading-from-version-5x-to-6x
/cc @fxn I haven't dug that far in yet, just wanted to post this in case people are wondering what happened. I'm not familiar with how this gets deploys, so pointers welcome :bow:

Bump puma and related dependencies

---

app/models/names_manager/canonical_names.rb
test/credits/canonical_names_test.rb

We've seen 29 commits from Eileen with author
```
Eileen <eileencodes@users.noreply.github.com>
```
All of them are merge commits, first one was https://github.com/rails/rails/commit/2cf763e8b6963118460f1cff30cc3fd103391602 by the end of March this year.
This patch updates credit in the app.
/cc @eileencodes ❤️

Map Eileen
