rails/rails-contributors

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
The latest commit have my name as 'Ankit gupta' (g lowercase).  Adding here would list those commits also in contrib list.
Thanks
=> Managing my name

app/models/names_manager/canonical_names.rb, app/models/names_manager/false_positives.rb, test/credits/canonical_names_test.rb, test/credits/false_positives_test.rb
Based on https://github.com/rails/rails/commit/319baed48e5ddb6556bcb3a89914dabf87171995
/cc @sh6khan
=> Add credits to Sadman Khan

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
=> defines an alias for Jon Moss

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Because for some reason I made a bunch of commits with 
"Claudio B <claudiob@users.noreply.github.com>" :sweat:
=> Add an alias for claudiob

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
* Added a mapping of my username to name to aggregate with my other contrib.
=> Map oss92 to Mohamed Osama

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
map my short committer name "Girish S" to "Girish Sonawane"
=> map Girish S to Girish Sonawane

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Hi, Xavier!
Please check my code.
p.s. it is your name, not surname, right?
=> Add new canonical name for Neodelf

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Hola @fxn!
My first PR to Rails has been merged 🎉 and I realized – after ages with the same gitconfig – that my name is not properly spelled! Fortunately you have a way to fix it in the contributors list 😊  
Gràcies! ❤️ 
PS: I've fixed my gitconfig 💩
=> spell López properly

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
There are some commits with no contributors.
I investigated every commit and added some maps.
```ruby
[4] pry(main)> Commit.with_no_contributors.exists?
Commit Exists (22.6ms)  SELECT  1 AS one FROM "commits" LEFT OUTER JOIN contributions ON commits.id = contributions.commit_id WHERE "contributions"."commit_id" IS NULL LIMIT $1  [["LIMIT", 1]]
=> false
```
=> Add some maps

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
I changed my username in the past few years since previous commits. While running the test suite I found a failing test and fixed that as well. 😄
=> add new canonical name for stve

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
This PR will bring together the name of [y-yagi](https://github.com/y-yagi).
=> Yuuji Yaginuma and Yuji Yaginuma are same contributor

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
=> define name for neumayr

Gemfile, doc/install.md
* Use github shorthand in Gemfile.
* Update install document (Update Ruby version to 2.4.4 from 2.4.1)
=> Use GitHub shorthand

.circleci/config.yml, app/models/contributor.rb
* Use `left_joins` in Contributor model.
* Don't use rocket hash.
* Configured CircleCI to check all tests are passed or not (Could you please enable CircleCI ?)
=> Refactor contributor model

Gemfile, doc/install.md
Seems it need to install libsodium-dev before setup.
If it not installed, it cause error on ffi.
=> Add libsodium-dev installation step to install.md

app/models/commit.rb
* Used `left_joins` with `.with_no_contributors`
* Modified where clause to be simple.
=> Refactor commit

README.md
Hello,
This pull request is a tiny typo fix (stemming from https://github.com/rails/rails-contributors/commit/c12b4485605875c920ffd220d81dad63579b5683#diff-04c6e90faac2675aa89e2176d2eec7d8).
Have a nice day !
=> Fix a tiny typo in README

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
This PR will bring together the name of shioimm.
=> Misaki Shioi and shioimm are same contributor

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Ali Ibrahim and alimi are the same person, map their commits so it shows
up correctly on the contributors list.
=> Combine Ali Ibrahim and alimi

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
https://contributors.rubyonrails.org/contributors/kp/commits
Email is taken from one of the commit: https://github.com/rails/rails/commit/8641de93eb98d4ebdb0db2530c8c79c0c4e2f95e.patch
Name is taken from GitHub profile: @KeithP
=> Add mapping for Keith Payne

app/models/names_manager/hard_coded_authors.rb, test/credits/hard_coded_authors_test.rb
References
- https://github.com/rails/rails/commit/1d133e8a4725439e4a61d53ce913eba9dcab42d3
- https://github.com/rails/rails/pull/38124#issuecomment-571844508
<details>
---
---
https://contributors.rubyonrails.org/contributors/direct_upload_xls_in_chrome/commits
</details>
=> Fix author of 1d133e8

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
I'm listed as 'Petrik' and 'Petrik de Heus'
=> Add mapping for Petrik de Heus

app/models/names_manager/canonical_names.rb
=> Add mapping for David Auza

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
[Zhang Kang](https://contributors.rubyonrails.org/contributors/zhang-kang/commits) is my canonical name and [piecehealth](https://contributors.rubyonrails.org/contributors/piecehealth/commits) is my nickname, please help to merge them, thanks.
=> fix credit: piecehealth -> Zhang Kang

app/models/names_manager/hard_coded_authors.rb, test/credits/hard_coded_authors_test.rb
Related to
https://github.com/rails/rails/pull/39697
https://github.com/rails/rails/pull/31435
=> Fix author of fdbc55b and 6c6c3fa

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
=> Fixed commit issue for alkesh26

app/views/faqs/show.html.erb
"in about its first four years" doesn't quite make sense. This change
should be a bit more clear!
Additionally, I felt it the end of this sentence could be made more
clear as well.
=> Correct typo

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb, test/credits/false_positives_test.rb
This completes the name change.
=> Updates credits for Siân Griffin contributions

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
👋  I would love for some of my older commits (like https://github.com/rails/rails/commit/8f5f2bf915f43fe7165440460830c5939af10ad8) to be rolled up since I started using my full name with git.
=> canonical_name for myself

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
I changed my name, and I've got 3 commits under Kevin Newton and all my old commits under Kevin Deisz. This consolidates them.
=> Kevin Deisz -> Kevin Newton

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
I have 17 commits on `dixpac` handle, others are on `Dino Maric`.
=> dixpac -> Dino Maric

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Tested locally in docker, worked well. :)
=> Canonicalize Maxim Chernyak as Max Chernyak

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
* Added the mapping and test.
FYI the [docker setup instructions](https://github.com/rails/rails-contributors/blob/master/doc/docker.md) aren't working for me on an M1.  I'll have to let the CI take care of verifying my test.
> docker-compose up -d
dc/exec bundle install
dc/rails db:setup
rails aborted!
LoadError: cannot load such file -- nokogiri/nokogiri
=> Map jpd800 -> Jacob Duffy

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
=> Add Joe Dupuis as alias for Joé Dupuis

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
=> map 'Kang Zhang' to 'Zhang Kang'

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Added a mapping for my name
akhilgkrishnan  -> Akhil G Krishnan
=> Add a canonical mapping to akhilgkrishnan

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
Hi @jonathanhefner as requested, here is the mapping for my contribution on https://github.com/rails/rails/pull/50044
=> Add chaadow mapping to Chedli Bourguiba

app/assets/stylesheets/screen.scss
- Hide sidebar toggle on desktop mode
- Make tables scrollable on mobile
=> Small tweaks

app/models/names_manager/canonical_names.rb, test/credits/canonical_names_test.rb
https://calebhearth.com/why-hearth
=> Re-credit Caleb Thompson => Caleb Hearth
